spring.application.name=forum
server.port=8081
api.key=4ed26428aed23bb35cf15076f0baadf8
spring.datasource.url=jdbc:mysql://localhost:3306/forumdiscussion
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=harinipandiraju07@gmail.com
spring.mail.password=xdyu fnhx fqvr gzqt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true